### YamlMime:Role 
title: DevOps 工程師 
metadata: 
  title: DevOps 工程師  
  description: DevOps 工程師將人員、流程與技術相結合、不斷提供有價值的產品與服務、以滿足終端使用者的需求與業務目標。 
uid: role.devops-engineer 
summary: | 
  DevOps 工程師將人員、流程與技術相結合、不斷提供有價值的產品與服務、以滿足終端使用者的需求與業務目標。
subTitle: DevOps 工程師將人員、流程與技術相結合、不斷提供有價值的產品與服務、以滿足終端使用者的需求與業務目標。
certificationPaths: 
- title: DevOps Engineer
  linkedInKeywords: DevOps Engineer
  uid: certification-path.devops-engineer
  prerequisites: 
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.azure-administrator
    levels:
    - intermediate
  - uid: certification.azure-developer
    levels:
    - intermediate
  - uid: certification.devops-engineer
    levels:
    - advanced    
certifications:
- uid: certification.devops-engineer
  requiredExams:
  - uid: exam.az-400
resources:
- title: Microsoft 訓練和認證指南
  description: 在簡明的訓練和認證指南中探索所有認證。
  href: https://aka.ms/TrainingCertDeck
- title: 訓練和認證海報
  description: 透過此訓練和認證海報選取您的成功路徑。
  href: https://aka.ms/traincertposter
- title: 支持認證
  href: ../help.md
  description: 通過Microsoft認證支持論壇獲得幫助。論壇主持人將在周一至週五的一個工作日內做出回應。
