### YamlMime:Role 
title: Functional Consultant [功能顧問] 
metadata: 
  title: Functional Consultant [功能顧問] 
  description: 功能顧問利用Microsoft Dynamics 365和Microsoft Power Platform來預測和計劃客戶需求。 
uid: role.functional-consultant 
summary: | 
  功能顧問利用Microsoft Dynamics 365和Microsoft Power Platform來預測和計劃客戶需求。
subTitle: 功能顧問利用Microsoft Dynamics 365和Microsoft Power Platform來預測和計劃客戶需求。
certificationPaths: 
- title: Dynamics 365 Customer Service Functional Consultant [Dynamics 365 客戶服務功能顧問]
  linkedInKeywords: Dynamics 365 Customer Service Functional Consultant [Dynamics 365 客戶服務功能顧問]
  uid: certification-path.d365-functional-consultant-customer-service 
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-customer-service
    levels:
    - intermediate
    
- title: Dynamics 365 Field Service Functional Consultant [Dynamics 365 現場服務功能顧問]
  linkedInKeywords: Dynamics 365 Field Service Functional Consultant [Dynamics 365 現場服務功能顧問]
  uid: certification-path.d365-functional-consultant-field-service 
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-field-service
    levels:
    - intermediate

- title: Dynamics 365 Finance Functional Consultant [Dynamics 365 財務功能顧問]
  linkedInKeywords: Dynamics 365 Finance Functional Consultant [Dynamics 365 財務功能顧問]
  uid: certification-path.d365-functional-consultant-financials 
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-financials
    levels:
    - intermediate


- title: Dynamics 365 Manufacturing Functional Consultant [Dynamics 365 製造業功能顧問]
  linkedInKeywords: Dynamics 365 Manufacturing Functional Consultant [Dynamics 365 製造業功能顧問]
  uid: certification-path.d365-functional-consultant-manufacturing
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-manufacturing
    levels:
    - intermediate

- title: Dynamics 365 Marketing Functional Consultant [Dynamics 365 行銷功能顧問]
  linkedInKeywords: Dynamics 365 Marketing Functional Consultant [Dynamics 365 行銷功能顧問]
  uid: certification-path.d365-functional-consultant-marketing 
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-marketing
    levels:
    - intermediate

- title: Dynamics 365 Sales Functional Consultant [Dynamics 365 銷售功能顧問]
  linkedInKeywords: Dynamics 365 Sales Functional Consultant [Dynamics 365 銷售功能顧問]
  uid: certification-path.d365-functional-consultant-sales 
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-sales
    levels:
    - intermediate

- title: Dynamics 365 Supply Chain Management Functional Consultant [Dynamics 365 供應鏈管理功能顧問]
  linkedInKeywords: Dynamics 365 Supply Chain Management Functional Consultant [Dynamics 365 供應鏈管理功能顧問]
  uid: certification-path.d365-functional-consultant-supply-chain-management
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-supply-chain-management
    levels:
    - intermediate

certifications:
- uid: certification.d365-functional-consultant-customer-service
  requiredExams:
  - uid: exam.mb-200
  - uid: exam.mb-230  

- uid: certification.d365-functional-consultant-field-service
  requiredExams:
  - uid: exam.mb-200
  - uid: exam.mb-240

- uid: certification.d365-functional-consultant-financials
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-310  


- uid: certification.d365-functional-consultant-manufacturing
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-320  

- uid: certification.d365-functional-consultant-marketing
  requiredExams:
  - uid: exam.mb-200
  - uid: exam.mb-220  

- uid: certification.d365-functional-consultant-sales
  requiredExams:
  - uid: exam.mb-200
  - uid: exam.mb-210  

- uid: certification.d365-functional-consultant-supply-chain-management
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-330  
- uid: certification.power-platform-functional-consultant-associate
  requiredExams:
  - uid: exam.pl-200  
- uid: certification.d365-business-central-functional-consultant-associate
  requiredExams:
  - uid: exam.mb-800
resources:
- title: Microsoft 訓練和認證指南
  description: 透過一份簡潔的訓練和認證指南探索所有認證。
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWtQJJ
- title: 訓練和認證海報
  description: 透過此訓練和認證海報選取您的成功路徑。
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PjDI
- title: 支援認證
  href: ../help.md
  description: 透過 Microsoft Certification 支援論壇取得幫助。論壇主持人將在週一至週五的一個工作日內做出回應。
